services:

  web:
    build: .
    image: busyness:latest
    hostname: web
    env_file:
      - ./.env
    volumes:
      - ./project:/project
      - ./static:/static
      - ./locale:/locale
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pycrm
    ports:
    - 8032:5432

volumes:
  db-data: