# Generated by Django 4.0.5 on 2022-06-11 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pitch', models.TextField(blank=True, default=None, null=True)),
                ('profile', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
