# Generated by Django 4.0.5 on 2022-06-16 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('relation_type', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='crm.entity')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='crm.entity')),
            ],
        ),
    ]
